Convert video settings from xblock metadata into the redux store. In-progress draft. TNL-10009.
edx/frontend-lib-content-components pull request #119
Opened 2022-09-23 21:56 UTC by kenclary

2022-09-30 16:03 UTC, KristinAoki commented
Have your rebased with `main` and checked that this works correctly with the updated widgets?

2022-09-30 20:33 UTC, KristinAoki commented on src/editors/data/redux/thunkActions/video.js
> +    fallbackVideos,
Do we need to add videoId here?

2022-09-30 22:43 UTC, rayzhou-bit commented on src/editors/data/redux/thunkActions/video.js
> +    fallbackVideos,
Good catch. I put it in

2022-10-03 16:03 UTC, KristinAoki requested changes

2022-10-04 16:07 UTC, rayzhou-bit commented on src/editors/data/redux/thunkActions/video.js
> +    edxVideoId: selectors.app.blockValue.data.metadata.edx_video_id,
I updated based on how you coded `deleteTranscript()` with `getState`. Updated tests and mockApi as well.

2022-10-04 17:13 UTC, KristinAoki approved these changes

2022-10-04 18:59 UTC, merged