Test: editor header component
edx/frontend-lib-content-components pull request #20
Opened 2022-02-22 22:41 UTC by rayzhou-bit

2022-02-22 22:47 UTC, rayzhou-bit commented on src/editors/components/EditorHeader/HeaderTitle.test.jsx
> +import React from 'react';
WIP

2022-02-22 22:47 UTC, rayzhou-bit commented on src/editors/components/EditorHeader/index.test.jsx
>  import React from 'react';
WIP

2022-02-23 15:47 UTC, connorhaugh commented
Note: make sure to remove any lint errors from files you edit as you work on them, so that we might move toward not having everything fail on lint errors.

2022-02-24 17:54 UTC, connorhaugh commented on src/editors/components/EditorHeader/HeaderTitle.test.jsx
> +  const hookProps = {
nit: perhaps consider renaming `hookprops`. That name implies that it is props for either the component, or the hook, when it is in fact the return value of the hook-- something we often refer to as a `state`. Just a nit though.

2022-02-24 17:57 UTC, connorhaugh commented on src/editors/containers/TextEditor/TextEditor.jsx
> +  console.log({
we can get rid of this console log.

2022-02-24 17:59 UTC, connorhaugh approved these changes
Nice-- this looks good. Just a couple of nits.

2022-02-24 20:37 UTC, muselesscreator commented on src/editors/components/EditorHeader/index.test.jsx
> +    el = shallow(<module.EditorHeader {...props} />);
React is weird about trying to do compoent like this (lowercase).
Recommend `const { EditorHeader } = module;  el = shallow(<EditorHeader {...props} />);`
(note: the snapshot is undefined in the snap file)

2022-02-24 20:38 UTC, muselesscreator commented on src/setupTest.js
> +    Spacer: 'ActionRow.Spacer',
++

2022-02-24 20:39 UTC, muselesscreator requested changes
One snapshot update needed.  Thanks for adding the ActionRow Spacer to the testUtils :-)

2022-02-25 16:13 UTC, muselesscreator approved these changes
lgtm

2022-02-25 17:15 UTC, merged