Feat  add autocreate new xblock
edx/frontend-lib-content-components pull request #67
Opened 2022-04-26 08:31 UTC by connorhaugh

2022-05-10 13:50 UTC, connorhaugh commented on src/editors/containers/EditorContainer/index.scss
> +.pgn__modal-layer {
We need to remove this again, right?

2022-05-16 19:18 UTC, rayzhou-bit requested changes
There's one bit of code that should be changed. Otherwise this looks really nice. Very simple and elegant solution to adding a new block.

2022-05-16 19:18 UTC, rayzhou-bit commented on www/src/Gallery.jsx
> +
blockTypes is not an array here and will trigger an error.
Something like the following code should work.
```
          { Object.values(blockTypes).map((e) => (
            <Form.Radio value={e}> {e} </Form.Radio>
          ))}
```

2022-05-16 20:11 UTC, rayzhou-bit approved these changes
lgtm!

2022-05-16 20:14 UTC, merged